[network]
director_ip_addr = "127.0.0.1"
director_port = 40000
heartbeat_interval_ms = 2000

[misc]
greeting_msg = "Hello brother"

[behavior]
dump_file = "pyfaas_worker/worker_dump.bin"
shutdown_persistence = false

[behavior.caching]
policy = "LRU"
max_size = 0

# [behavior.exec_limits]
# cpu_time_limit_s = 5
# address_space_limit_mb = 100

[logging]
log_level = "debug"
log_directory = "pyfaas_worker/logs"
log_filename = "worker_log.log"

[statistics]
enabled = true
